# Dynmap-TAN configuration
#
update:
  # Seconds between checks for TownsAndNations updates
  period: 300

layer:
  # Name of the layer
  name: "Towns and Nations"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layer_priority: 0
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0


# Format for popup - substitute values for macros: use %<flagname>% for value of specific flag
town_infowindow:
  start: '<div class="infowindow">'
  name: '<span style="font-size:140%;font-weight:bold;">%TOWN_NAME%</span>  <span style="font-size:80%">Créé il y a %DAYS_SINCE_CREATION% jour(s)</span><br><br>'
  description: '<span style="font-size:100%;font-style:italic;">%TOWN_DESCRIPTION%</span><br>'
  data: '<hr><span style="font-size:100%;"><b>Claims</b> %NUMBER_CLAIMS% <b>|</b> <b>Niveau</b> %TOWN_LEVEL% </span><hr><br>'
  region: '<span style="font-weight:bold;">Région:</span><br>%REGION_NAME%<br><br>'
  leader: '<span style="font-weight:bold;">Leader de la ville</span><br>%TOWN_LEADER%<br><br>'
  members: '<span style="font-weight:bold;">Membres</span><br>%MEMBERS_LIST%<br>'
  end: '</div>'

region_infowindow:
  start: '<div class="infowindow">'
  name: '<span style="font-size:140%;font-weight:bold;">%REGION_NAME%</span>  <span style="font-size:80%">Créé il y a %DAYS_SINCE_CREATION% jour(s)</span><br><br>'
  description: '<span style="font-size:100%;font-style:italic;">%REGION_DESCRIPTION%</span><br>'
  data: '<hr><span style="font-size:100%;"><b>Claims</b> %NUMBER_CLAIMS% <b>|</b> <b>Nombre de villes</b> %NUMBER_OF_TOWNS% </span><hr><br>'
  capital: '<span style="font-weight:bold;">Capitale régionale</span><br>%REGION_CAPITAL%<br><br>'
  cities: '<span style="font-weight:bold;">Villes</span><br>%TOWN_LIST%<br>'
  end: '</div>'

fieldstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
