# Dynmap-TAN configuration
#
update:
  # Seconds between checks for TownsAndNations_dynmap updates
  period: 300

chunk_layer:
  # Name of the layer
  name: "Towns and Nations"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in layer menu (low goes before high - default is 0)
  priority: 0
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0

#Landmarks layer
landmark_layer:
  # Name of the layer
  name: "Towns and Nations - landmarks"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in layer menu (low goes before high - default is 0)
  priority: 1
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0


# Format for popup - substitute values for macros: use %<flagname>% for value of specific flag
#%TOWN_NAME% - Name of the town
#%REGION_NAME% - Name of the region
#%DAYS_SINCE_CREATION% - Number of days since the town or region was created
#%DESCRIPTION% - Description of the town or region
#%NUMBER_CLAIMS% - Number of claims in the town or region
#%TOWN_LEADER% - Leader of the town
#%TOWN_LEVEL% - Level of the town
#%MEMBERS_LIST% - List of members in the town
#%NUMBER_OF_TOWNS% - Number of towns in the region
#%TOWN_LIST% - List of towns in the region
#%REGION_CAPITAL% - Capital of the region
town_infowindow: '<div class="infowindow"><span style="font-size:140%;font-weight:bold;">%TOWN_NAME%</span>  <span style="font-size:80%">Created %DAYS_SINCE_CREATION% day(s) ago</span><br><br><span style="font-size:100%;font-style:italic;">%DESCRIPTION%</span><br><hr><span style="font-size:100%;"><b>Claims</b> %NUMBER_CLAIMS% <b>|</b> <b>Level</b> %TOWN_LEVEL% </span><hr><br><span style="font-weight:bold;">Region:</span><br>%REGION_NAME%<br><br><span style="font-weight:bold;">Leader</span><br>%TOWN_LEADER%<br><br><span style="font-weight:bold;">Members</span><br>%MEMBERS_LIST%<br></div>'
region_infowindow: '<div class="infowindow"> <span style="font-size:140%;font-weight:bold;">%REGION_NAME%</span>  <span style="font-size:80%">Created %DAYS_SINCE_CREATION% day(s) ago</span><br><br><span style="font-size:100%;font-style:italic;">%DESCRIPTION%</span><br><hr><span style="font-size:100%;"><b>Claims</b> %NUMBER_CLAIMS% <b>|</b> <b>Number of towns</b> %NUMBER_OF_TOWNS% </span><hr><br><span style="font-weight:bold;">Capital</span><br>%REGION_CAPITAL%<br><br><span style="font-weight:bold;">Towns</span><br>%TOWN_LIST%<br></div>'

landmark_infowindow: '<div class="infowindow"><span style="font-size:140%;font-weight:bold;">Landmark</span><span style="font-size:100%;font-style:italic;"><br><hr><span style="font-size:100%;"><b>Owner</b></span><br>%OWNER%</div><b>Producing<br></b> %QUANTITY%x %ITEM%</span>'


town_fieldStyle:
  baseStrokeColor: "#FF0000" #Not implemented yet, chunk color from the town will override
  strokeOpacity: 0.8
  strokeWeight: 3
  baseFillColor: "#FF0000" #Not implemented yet, chunk color from the town will override
  fillOpacity: 0.35

region_fieldStyle:
  baseStrokeColor: "#FF0000" #Not implemented yet, chunk color from the town will override
  strokeOpacity: 0.6
  strokeWeight: 3
  baseFillColor: "#FF0000" #Not implemented yet, chunk color from the town will override
  fillOpacity: 0.2

