name: Towns_And_Nations_Dynmap
version: '${version}'
main: org.leralix.towns_and_nations_dynmap.TownsAndNations_Dynmap
api-version: '1.20'
depend:  [TownsAndNations, dynmap]
commands:
  tanmap:
    description: base command of Town and Nation dynmap
    permission: townandnation_dynmap.base
    usage: /<command>